

SELECT*
FROM SOLSOLDADOR
WHERE SINETE LIKE '%GBJ-04%'
ORDER BY SINETE

// ---------------------------------------


SELECT SINETE,AREA,NOME,EMPRESA
FROM SOLSOLDADOR
WHERE SINETE='GBJ-0167'
OR SINETE='GBJ-0257'
OR SINETE='GBJ-0306'
OR SINETE='GBJ-0346'
OR SINETE='GBJ-0352'

UNION

SELECT SINETE,AREA,NOME,EMPRESA
FROM SOLSOLDADOR
WHERE SINETE LIKE '%GBJ-04%'

// -----------------------------------------

SELECT*
FROM SOQSOL_QUALIFICACAO
WHERE DTQUALI = '26.01.2022'
