
SELECT 
JNT.COD_JUNTA  AS JOINT,
SUBSTRING(TRE.SOLDADORES FROM 6 FOR 8) AS WELDER_ID_SIGNET,
SUBSTRING(TRE.SOLDADORES FROM 1 FOR 4) AS WELD_PROC,
'Ultrasonic Testing' AS INSPECTION,
'IE - Note 1' AS DEFECT_TYPE,
DFT.FILMESREPROVADOS AS QTY_FILM,
DFT.FILMESREPROVADOS AS REPROVED_FILM,
DFT.EXTENSAOINSP AS INSPECTED_LENGTH,
'VER LOCAL' AS DEFECT_LOCAL,
DFT.EXTENSAODEF AS DEFECT_LENGTH,
DFT.PROF AS PROF_DEFEITO,
DFT.TIPO_DEFEITO,
JNT.ESPESSURA1,
JNT.ESPESSURA2,
JNI.TIPO_JUNTA


      FROM TRETRECHO TRE 
      INNER JOIN JNTJUNTA JNT ON TRE.PJNTJUNTA = JNT.BOLD_ID
      INNER JOIN VW_DEFEITOS DFT ON DFT.COD_TRECHO = TRE.COD_TRECHO 
      INNER JOIN VW_JUNTAINSPECIONADA JNI ON JNI.COD_JUNTA = JNT.COD_JUNTA 

           WHERE DFT.DATA>= '2022-01-16'
               ORDER BY 2


//-------------------------------------------


SELECT 
SOL.EMPRESA,SOL.AREA,
SOL.SINETE,
SOL.DTENTRADA,
SOL.DTSAIDA

     FROM SOLSOLDADOR SOL
     LEFT JOIN SOQSOL_QUALIFICACAO SOQ ON ( SOL.BOLD_ID = SOQ.PSOLSOLDADOR )
     LEFT JOIN HDQHISTORICO_DTQUALI HDQ ON ( HDQ.PSOQQUALI = SOQ.BOLD_ID ) 
             WHERE SOL.AREA = 'JURONG'
                          ORDER BY 2,1