
-- SITUAÇÃO DAS JUNTAS DO FD

-------------------------------
--DF- COM PENDENCIA
SELECT 
CASE 
  WHEN 
     PECA_1 IS NULL 
     THEN SUB_MONTAGEM 
      ELSE PECA_1 END AS DF,
COUNT(COD_JUNTA) AS QTD_JUNTA,
'Com Pendencia'

FROM VW_JUNTAINSPECIONADA
WHERE COD_JUNTA NOT LIKE '#%' AND STATUS_JUNTA NOT LIKE 'Finaliz%'

GROUP BY DF
ORDER BY 1


-------------------------------
--DF- TODAL DE JUNTAS
SELECT 
CASE 
  WHEN 
     PECA_1 IS NULL 
     THEN SUB_MONTAGEM 
      ELSE PECA_1 END AS DF,
COUNT(COD_JUNTA) AS QTD_JUNTAS

FROM VW_JUNTAINSPECIONADA
WHERE COD_JUNTA NOT LIKE '#%' 

GROUP BY DF
ORDER BY 1

------------------------------------------------

SELECT 
COD_JUNTA,
TIPO,
COUNT(CASE WHEN TIPO = 'MNT' OR TIPO ='PMN' OR TIPO ='EDF' THEN '1' ELSE '0' END AS OBS)

FROM VW_JUNTAINSPECIONADA
WHERE COD_JUNTA NOT LIKE '#%' 

GROUP BY COD_JUNTA,TIPO